name: Regular Check

on:
  workflow_dispatch:
jobs:
  test:
    name: echo test
    runs-on: ubuntu-latest
    steps:
      - name: Echo name
        run: echo "Hi disha"
        
      - name: It will fail
        run: return -1
