name: Regular Check

on:
  workflow_run:
    workflows: [Regular Check]
    types: [completed]
  workflow_dispatch:
jobs:
  test:
    name: echo test
    runs-on: ubuntu-latest
    if: |
        (${{ github.event.workflow_run.conclusion == 'failure' }} && ${{ github.event.workflow_run.run_attempt < 2 }}) ||
        (${{ github.event.workflow_run.run_attempt < 1 }})
    steps:
      - name: Echo name
        run: echo "Hi disha"
              echo github.event.workflow_run.conclusion
              echo github.event.workflow_run.run_attempt
        
      - name: It will fail
        run: return -1
