name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Throw fail
        run: exit 1
      
      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MS_MAIL_USERNAME}}
          password: ${{secrets.MS_MAIL_PASSWORD}}
          subject: Github Actions job result
          to: dishainwati@gmail.com, t-dinwati@microsoft.com
          from: Disha Inwati gmail
          secure: true
          body: Build job of - ${{github.repository}} failed! ACTOR- ${{github.actor}} ACTION ${{github.action}} JOBID ${{github.job}} STEP SUMMARY - ${{github.step.summary}}
          priority: low
